### ISSUE TITLE
Not Compatible with windows 64 bit

### ISSUE THREAD

**Issue by ayushi23** [albanm/node-libxml-xsd#18]
We have been facing issues while installing the libxml-xsd package.

Error in console:

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\ayushi.COMPRO\AppData\Roaming\nvm\v5.5.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Users\ayushi.COMPRO\AppData\Roaming\nvm\v5.5.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ayushi.COMPRO\\AppData\\Roaming\\nvm\\v5.5.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\npm\node_modules\libxmljs-mt
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:libxmljs-mt@0.16.1 libxmljs-mt@0.16.1 install: `node-gyp rebuild`
npm WARN install:libxmljs-mt@0.16.1 Exit status 1
npm@3.3.12 C:\Program Files\nodejs\node_modules\npm
├── bindings@1.2.1  extraneous
└── nan@2.5.1  extraneous

**Comment by Nokel81** [comment]
You have to add an environment variable `PYTHON` environment to the path of your installed python 2.X version. Then you have to run the `npm i --save libxml-xsd` command in command prompt in administrator mode for it to work.
