### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by faizanvahevaria** [albanm/node-libxml-xsd#34]
I am installing in my nodejs project 
using 'npm i libxml-xsd' command.

I am getting following errors...
Please help me to resolve this error....

> libxmljs-mt@0.16.1 install /home/vi109/Faizan-Vahevaria/StarUML/staruml-cefact/node_modules/libxmljs-mt
> node-gyp rebuild

make: Entering directory '/home/vi109/Faizan-Vahevaria/StarUML/staruml-cefact/node_modules/libxmljs-mt/build'
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
../src/libxmljs.cc: In function ‘void libxmljs::adjustMem(ssize_t)’:
../src/libxmljs.cc:69:17: error: ‘IsDead’ is not a member of ‘v8::V8’
     if (v8::V8::IsDead())
                 ^~~~~~
xmljs.target.mk:167: recipe for target 'Release/obj.target/xmljs/src/libxmljs.o' failed
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
make: Leaving directory '/home/vi109/Faizan-Vahevaria/StarUML/staruml-cefact/node_modules/libxmljs-mt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vi109/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.0.0-37-generic
gyp ERR! command "/usr/bin/node" "/home/vi109/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vi109/Faizan-Vahevaria/StarUML/staruml-cefact/node_modules/libxmljs-mt
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN gs-gs.staruml-cefact@0.2.5 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs-mt@0.16.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs-mt@0.16.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vi109/.npm/_logs/2020-02-06T13_15_25_283Z-debug.log

**Comment by ipratico** [comment]
Same error here. I want to migrate from node v8.12 to v12.18 but this library don't build. Anyone can help?

**Comment by ipratico** [comment]
@faizanvahevaria FYI: I'm currently trying this library **libxmljs2-xsd**, which is presented as an "XSD validation for node.js 14.x using libxml via libxmljs2"
