### ISSUE TITLE
installation fails under node v4

### ISSUE THREAD

**Issue by drom** [albanm/node-libxml-xsd#4]
run:
```
npm install libxml-xsd
```

Error:
```
drom@drom:~/work/a> npm install libxml-xsd
-
> libxmljs@0.11.1 install /home/drom/work/a/node_modules/libxml-xsd/node_modules/libxmljs
> node-gyp rebuild

gyp: /usr/lib64/node_modules/npm/node_modules/node-gyp/addon-rpm.gypi not found (cwd: /home/drom/work/a/node_modules/libxml-xsd/node_modules/libxmljs) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/configure.js:358:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.12-1-default
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/drom/work/a/node_modules/libxml-xsd/node_modules/libxmljs
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.1.12-1-default
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "libxml-xsd"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.11.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/drom/work/a/npm-debug.log
```

**Comment by albanm** [comment]
Can you check with latest release (0.4.0) ?

**Comment by drom** [comment]
Yes, I am getting the same error with the latest version from NPM
