### ISSUE TITLE
Crash when simply including libxml-xsd

### ISSUE THREAD

**Issue by artworkad** [albanm/node-libxml-xsd#5]
Simply including the library:

```
xsd = require('libxml-xsd')
```

causes following crash:

```
/Users/foobar/Documents/Dev/foo/code/foo-api/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: dlopen(/Users/foobar/Documents/Dev/foo/code/foo-api/node_modules/libxml-xsd/build/Release/node-libxml-xsd.node, 1): Symbol not found: __ZN8libxmljs20XmlSyntaxErrorsStore9ErrorFuncEPvP9_xmlError
  Referenced from: /Users/foobar/Documents/Dev/foo/code/foo-api/node_modules/libxml-xsd/build/Release/node-libxml-xsd.node
  Expected in: /Users/foobar/Documents/Dev/foo/code/foo-api/node_modules/libxmljs/build/Release/xmljs.node

    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/Users/foobar/Documents/Dev/foo/code/foo-api/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/foobar/Documents/Dev/foo/code/foo-api/node_modules/libxml-xsd/index.js:8:34)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/foobar/Documents/Dev/foo/code/foo-api/api/controllers/RateController.js:42:12
    at cb (/Users/foobar/Documents/Dev/foo/code/foo-api/node_modules/skipper/standalone/Upstream/prototype.upload.js:82:14)
```

I am using node 4.2.2, libxml-xsd 0.4, libxmljs 0.16.1 on OSX el captian. Merry XMAS tho :santa:

**Comment by albanm** [comment]
Hello,

If I remember correctly this looks like some bug I had when including 2 different versions of libxmljs.

I just released a version that exports the internal libxmljs of libxml-xsd, could you try like this ? See [here](https://github.com/albanm/node-libxml-xsd#libxmljs-integration).

**Comment by oamaok** [comment]
Running `npm rebuild` once fixed the problem for me.

**Comment by saberworks** [comment]
I ran into this.  It was because I libxml-xsd pulls in libxmljs-mt which is a fork of libxmljs, and my project also called for libxmljs directly.  Having both libxmljs and libxmljs-mt installed at the same time caused conflicts and a crash with the same or very similar error message.  My solution was to get rid of libxmljs and instead just use libxmljs-mt (the interface is the same).  Note that using npm to install both doesn't report any errors, it's just a runtime crash when simply including one of them when both are installed.  Running `npm rebuild` as suggested did not help in my case.
